name: 'Publish and Deploy'

on:
    push:
        branches: [master]     # 当 push 到 master 分支时自动触发
    workflow_dispatch:         # 同时保留手动触发功能
        inputs:
            build_windows_x86_64:
                description: 'Build for Windows x86_64'
                required: false
                type: boolean
                default: true

permissions:
    contents: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: 'windows-latest'
                      target: 'x86_64-pc-windows-msvc'
                      args: ''
                      enabled: ${{ github.event.inputs.build_windows_x86_64 == 'true' || github.event_name == 'push' }}

        runs-on: ${{ matrix.platform }}
        timeout-minutes: 60
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check Tauri
              shell: bash
              run: |
                  if [ -z "${{ secrets.TAURI_KEY_PASSWORD }}" ]; then
                    echo "::error::TAURI_KEY_PASSWORD is required but not set."
                    exit 1
                  fi

            - name: Install rust target
              run: rustup target add ${{ matrix.target }}

            - uses: pnpm/action-setup@v3
              with:
                  version: latest

            - name: Sync node version and setup cache
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Install frontend dependencies
              run: pnpm install

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: 'PakePlus-v__VERSION__'
                  releaseName: 'PakePlus v__VERSION__'
                  body_path: ./Note.md
                  releaseDraft: true
                  prerelease: false
                  args: ${{ matrix.args }}